# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180222_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
