# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180223_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
