# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20180224_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashurl',
            name='url',
            field=models.CharField(max_length=250, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
